#!/usr/bin/env bash
# Generate coordinator/.env and team token handout for a 6-team event.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/coordinator/.env"
TOKEN_FILE="$ROOT_DIR/coordinator/team_tokens.tsv"
TEAM_SUFFIXES_CSV="${TEAM_SUFFIXES:-1,2,3,4,5,6}"
OPENROUTER_VALUE="${OPENROUTER_API_KEY:-replace_before_event}"
FORCE=0

usage() {
  cat <<'EOF'
Usage: scripts/setup_admin_env.sh [--force] [--openrouter-api-key KEY]

Creates:
  coordinator/.env
  coordinator/team_tokens.tsv
  data/ repos/ vuln_specs/

Default teams: team1~team6.
Override with TEAM_SUFFIXES=1,2,3,4,5,6 before running if needed.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --force)
      FORCE=1
      shift
      ;;
    --openrouter-api-key)
      OPENROUTER_VALUE="${2:?--openrouter-api-key requires a value}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  echo "Refusing to overwrite existing $ENV_FILE"
  echo "Use --force only when you intentionally want new secrets."
  exit 1
fi

secret() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

IFS=',' read -r -a SUFFIXES <<< "$TEAM_SUFFIXES_CSV"
mkdir -p "$ROOT_DIR/coordinator" "$ROOT_DIR/data" "$ROOT_DIR/repos" "$ROOT_DIR/vuln_specs"
tmp_env="$(mktemp)"
tmp_tokens="$(mktemp)"

{
  echo "# Generated by scripts/setup_admin_env.sh"
  echo "# Regenerate only before distributing team tokens."
  echo
  echo "TEAM_SUFFIXES=$TEAM_SUFFIXES_CSV"
  echo "ADMIN_SECRET=$(secret)"
  echo "RUNNER_SECRET=$(secret)"
  echo "CHECKER_TOKEN=$(secret)"
  echo
  echo "# Team service tokens"
  for suffix in "${SUFFIXES[@]}"; do
    suffix="$(echo "$suffix" | tr '[:lower:]' '[:upper:]' | xargs)"
    echo "TOKEN_TEAM_${suffix}=$(secret)"
  done
  echo
  echo "# Defense-only tokens"
  for suffix in "${SUFFIXES[@]}"; do
    suffix="$(echo "$suffix" | tr '[:lower:]' '[:upper:]' | xargs)"
    echo "DEFENSE_TOKEN_TEAM_${suffix}=$(secret)"
  done
  echo
  echo "# Team service network defaults"
  echo "MANAGEMENT_HOST_PORT=42000"
  echo "PUBLIC_COORDINATOR_URL=http://knights.hspace.io:42000"
  index=0
  for suffix in "${SUFFIXES[@]}"; do
    suffix="$(echo "$suffix" | tr '[:lower:]' '[:upper:]' | xargs)"
    echo "IP_TEAM_${suffix}=10.89.21.$((10 + index))"
    echo "PORT_TEAM_${suffix}=8000"
    echo "HOST_PORT_TEAM_${suffix}=$((42001 + index))"
    index=$((index + 1))
  done
  echo
  echo "COORDINATOR_URL=http://localhost:42000"
  echo "HOOK_COORDINATOR_URL=http://127.0.0.1:9000"
  echo "OPENROUTER_API_KEY=$OPENROUTER_VALUE"
  echo "OPENROUTER_BASE_URL=https://openrouter.ai/api/v1"
  echo
  echo "DATA_DIR=/app/data"
  echo "DB_PATH=/app/data/game_state.db"
  echo "VULN_SPEC_DIR=/app/vuln_specs"
  echo "REPOS_DIR=/app/repos"
  echo "POC_RUNNER_MODE=auto"
  echo "POC_DOCKER_NETWORK=hackathon_target-net"
  echo "POC_DOCKER_IMAGE=python:3.11-slim"
  echo "ALLOW_UNSAFE_AGENT_RUNS=0"
  echo "ALLOW_STUDENT_AGENT_RUNS=0"
} > "$tmp_env"

{
  printf "team\tteam_token\tdefense_token\tservice_ip\thost_port\n"
  index=0
  for suffix in "${SUFFIXES[@]}"; do
    suffix="$(echo "$suffix" | tr '[:lower:]' '[:upper:]' | xargs)"
    team="team${suffix}"
    team_token="$(grep "^TOKEN_TEAM_${suffix}=" "$tmp_env" | cut -d= -f2-)"
    defense_token="$(grep "^DEFENSE_TOKEN_TEAM_${suffix}=" "$tmp_env" | cut -d= -f2-)"
    printf "%s\t%s\t%s\t10.89.21.%s\t%s\n" "$team" "$team_token" "$defense_token" "$((10 + index))" "$((42001 + index))"
    index=$((index + 1))
  done
} > "$tmp_tokens"

mv "$tmp_env" "$ENV_FILE"
mv "$tmp_tokens" "$TOKEN_FILE"
chmod 600 "$ENV_FILE" "$TOKEN_FILE"

echo "Created $ENV_FILE"
echo "Created $TOKEN_FILE"
echo "Next:"
echo "  1. Put a real OPENROUTER_API_KEY in $ENV_FILE if not provided."
echo "  2. Share only each team's row from team_tokens.tsv."
echo "  3. Run: docker compose config --quiet && docker compose up -d --build"
